version: '3.8'

services:
  backend:
    image: somnathambati/smartvote_backend:latest
    container_name: smartvote-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - smartvote-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: somnathambati/smartvote_frontend:latest
    container_name: smartvote-nginx
    restart: always
    ports:
      - "9090:80"
    depends_on:
      - backend
    command: ["sh", "-c", "until curl -s http://smartvote-backend:5000/api/health; do echo waiting for backend; sleep 2; done; nginx -g 'daemon off;'"]
    networks:
      - smartvote-network

networks:
  smartvote-network:
    driver: bridge
