export const sName = [
    "Select State",
    "Andhra Pradesh ",
    "Arunachal Pradesh",
    "Assam",
    "Bihar ",
    "Chhattisgarh",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala ",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur ",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim ",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
  ];

  export const bName = ["Gender","Male","Female"];

  export const userType = ["Admin","Voter"];