apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL3NvbW5hdGhhbWJhdGk6aTdHeThLYng5eDVTbTNTZUBjbHVzdGVyMS53enp5ZS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZhcHBOYW1lPUNsdXN0ZXIx
  JWT_SECRET: TU9IRU5NT05EQUxKREZLRkxM  # Base64 encoded "...."
